name = "DayZed"; // name
picture = ""; // picture in expanded description
logoSmall = ""; // icon next to mod name when description is not expanded
logo = ""; // logo below game menu
logoOver = ""; // on mouse hover over logo
tooltip = "DayZed"; // tool tip on mouse hover
overview = "DayZed"; // overview
action = "https://DayZed.gg/"; // link
author = "DayZed"; // author
version = "0.80"; // version